export const states = [
  { id: 0, text: "Andhra Pradesh" },
  { id: 1, text: "Arunachal Pradesh" },
  { id: 2, text: "Assam" },
  { id: 3, text: "Bihar" },
  { id: 4, text: "Chhattisgarh" },
  { id: 5, text: "Goa" },
  { id: 6, text: "Gujarat" },
  { id: 7, text: "Haryana" },
  { id: 8, text: "Himachal Pradesh" },
  { id: 9, text: "Jammu and Kashmir" },
  { id: 10, text: "Jharkhand" },
  { id: 11, text: "Karnataka" },
  { id: 12, text: "Kerala" },
  { id: 13, text: "Madhya Pradesh" },
  { id: 14, text: "Maharashtra" },
  { id: 15, text: "Manipur" },
  { id: 16, text: "Meghalaya" },
  { id: 17, text: "Mizoram" },
  { id: 18, text: "Nagaland" },
  { id: 19, text: "Odisha" },
  { id: 20, text: "Punjab" },
  { id: 21, text: "Rajasthan" },
  { id: 22, text: "Sikkim" },
  { id: 23, text: "Tamil Nadu" },
  { id: 24, text: "Telangana" },
  { id: 25, text: "Tripura" },
  { id: 26, text: "Uttarakhand" },
  { id: 27, text: "Uttar Pradesh" },
  { id: 28, text: "West Bengal" },
  { id: 29, text: "Andaman and Nicobar Islands" },
  { id: 30, text: "Chandigarh" },
  { id: 31, text: "Dadra and Nagar Haveli" },
  { id: 32, text: "Daman and Diu" },
  { id: 33, text: "Delhi" },
  { id: 34, text: "Lakshadweep" },
  { id: 35, text: "Puducherry" },
]
export const courses = [
  { id: 0, text: "MBBS" },
  { id: 1, text: "BDS" },
  { id: 1, text: "BSc Nursing" },
]

export const categories = [
  { id: 0, text: "General" },
  { id: 1, text: "General-EWS" },
  { id: 2, text: "EWS" },
  { id: 3, text: "EWS-PwD" },
  { id: 4, text: "OBC" },
  { id: 5, text: "OBC-PwD" },
  { id: 6, text: "Open" },
  { id: 7, text: "Open-PwD" },
  { id: 8, text: "SC" },
  { id: 9, text: "SC-PwD" },
  { id: 10, text: "ST" },
  { id: 11, text: "ST-PwD" },
]
